# Generated by Django 3.1.3 on 2020-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_of_transfer', models.DateTimeField()),
                ('postcode', models.CharField(max_length=8)),
                ('property_type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flats/Maisonettes'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
