# Generated by Django 3.1.3 on 2020-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertysale',
            index=models.Index(fields=['date_of_transfer', 'postcode'], name='prices_prop_date_of_7ff332_idx'),
        ),
    ]
